### ISSUE TITLE
Failed to start sonarqube lts version

### ISSUE THREAD

**Issue by felipepiresdejesus** [vaulttec/sonar-auth-oidc#83]
After upgrading sonarqube to 2025-lta-developer version, the plugin is not working and sonarqube is not starting.

These are the logs:  

31 January 2025 at 08:23 (UTC+1:00) | Caused by: java.lang.NoClassDefFoundError: org/sonar/api/web/ServletFilter | sonarqube-container
-- | -- | --
31 January 2025 at 08:23 (UTC+1:00) | at java.base/java.lang.Thread.run(Unknown Source) | sonarqube-container
31 January 2025 at 08:23 (UTC+1:00) | at org.sonar.server.platform.PlatformImpl.start(PlatformImpl.java:217) | sonarqube-container
31 January 2025 at 08:23 (UTC+1:00) | at org.sonar.server.platform.PlatformImpl.startLevel34Containers(PlatformImpl.java:197) | sonarqube-container
31 January 2025 at 08:23 (UTC+1:00) | at org.sonar.server.platform.PlatformImpl$AutoStarterRunnable.runIfNotAborted(PlatformImpl.java:365) | sonarqube-container
31 January 2025 at 08:23 (UTC+1:00) | at org.sonar.server.platform.PlatformImpl$1.doRun(PlatformImpl.java:116) | sonarqube-container
31 January 2025 at 08:23 (UTC+1:00) | at org.sonar.server.platform.PlatformImpl$AutoStarterRunnable.run(PlatformImpl.java:349) | sonarqube-container
31 January 2025 at 08:23 (UTC+1:00) | at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:81) | sonarqube-container
31 January 2025 at 08:23 (UTC+1:00) | at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:757) | sonarqube-container
31 January 2025 at 08:23 (UTC+1:00) | java.lang.IllegalStateException: Fail to load plugin OpenID Connect Authentication for SonarQube [authoidc] | sonarqube-container
31 January 2025 at 08:23 (UTC+1:00) | 2025.01.31 07:23:44 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube | sonarqube-container
31 January 2025 at 08:23 (UTC+1:00) | 2025.01.31 07:23:41 INFO web[][o.s.s.p.DetectPluginChange] Detect plugin changes | sonarqube-container
31 January 2025 at 08:23 (UTC+1:00) | 2025.01.31 07:23:41 INFO web[][o.s.s.p.w.MasterServletFilter] Initializing servlet filter org.sonar.server.platform.web.WebServiceFilter@4fe2dd02 [pattern=UrlPattern{inclusions=[/api/system/migrate_db.*, ...], exclusions=[/api/components/update_key, ...]}]

**Comment by geigervlad** [comment]
same issue as https://github.com/vaulttec/sonar-auth-oidc/issues/81?
